# Generated by Django 3.2.3 on 2021-11-09 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('ubicacion', models.CharField(max_length=50)),
                ('km_parcial', models.FloatField()),
                ('temperatura', models.IntegerField()),
                ('visibilidad', models.CharField(max_length=50)),
                ('presion_atm', models.FloatField()),
                ('viento', models.FloatField()),
                ('precipitaciones', models.IntegerField()),
                ('radiacion_uv', models.IntegerField()),
                ('nivel_cota', models.FloatField()),
                ('estado_trafico', models.CharField(max_length=50)),
                ('calorias_quemadas', models.IntegerField()),
                ('pulsaciones', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('ubicacion_inicio', models.CharField(max_length=50)),
                ('ubicacion_fin', models.CharField(max_length=50)),
                ('fuente_velocidad', models.CharField(max_length=50)),
                ('velocidad_max', models.IntegerField()),
                ('velocidad_media', models.IntegerField()),
                ('velocidad_minima', models.IntegerField()),
                ('kms_recorrido', models.FloatField()),
                ('temperatura_media', models.IntegerField()),
                ('presion_atm_media', models.FloatField()),
                ('viento_predominante', models.CharField(max_length=50)),
                ('nivel_lluvias_media', models.FloatField()),
                ('estado_cota_media', models.FloatField()),
                ('estado_trafico_media', models.CharField(max_length=50)),
                ('calorias_quemadas', models.IntegerField()),
                ('pulsaciones_media', models.IntegerField()),
                ('co2_evitado', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('ingreso', models.BooleanField()),
                ('tipo_dispositivo', models.CharField(max_length=50)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50)),
                ('identificacion', models.IntegerField()),
                ('kms_recorridos_acumulados', models.FloatField()),
                ('timepo_recorridos_acumulados', models.IntegerField()),
                ('fecha_alta', models.DateField()),
                ('fecha_baja', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='ModelVehiculo',
        ),
        migrations.AddField(
            model_name='session',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.vehicle'),
        ),
        migrations.AddField(
            model_name='route',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.vehicle'),
        ),
        migrations.AddField(
            model_name='checkpoint',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.route'),
        ),
    ]
