# Generated by Django 3.2.3 on 2021-11-12 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='componente_parametro',
            name='tipo_componente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.tipo_componente'),
        ),
    ]
